// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt,
} from "@graphprotocol/graph-ts";

export class ValidationRequest extends ethereum.Event {
  get params(): ValidationRequest__Params {
    return new ValidationRequest__Params(this);
  }
}

export class ValidationRequest__Params {
  _event: ValidationRequest;

  constructor(event: ValidationRequest) {
    this._event = event;
  }

  get validatorAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get agentId(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get requestUri(): string {
    return this._event.parameters[2].value.toString();
  }

  get requestHash(): Bytes {
    return this._event.parameters[3].value.toBytes();
  }
}

export class ValidationResponse extends ethereum.Event {
  get params(): ValidationResponse__Params {
    return new ValidationResponse__Params(this);
  }
}

export class ValidationResponse__Params {
  _event: ValidationResponse;

  constructor(event: ValidationResponse) {
    this._event = event;
  }

  get validatorAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get agentId(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get requestHash(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }

  get response(): i32 {
    return this._event.parameters[3].value.toI32();
  }

  get responseUri(): string {
    return this._event.parameters[4].value.toString();
  }

  get responseHash(): Bytes {
    return this._event.parameters[5].value.toBytes();
  }

  get tag(): Bytes {
    return this._event.parameters[6].value.toBytes();
  }
}

export class ValidationRegistry extends ethereum.SmartContract {
  static bind(address: Address): ValidationRegistry {
    return new ValidationRegistry("ValidationRegistry", address);
  }

  getIdentityRegistry(): Address {
    let result = super.call(
      "getIdentityRegistry",
      "getIdentityRegistry():(address)",
      [],
    );

    return result[0].toAddress();
  }

  try_getIdentityRegistry(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getIdentityRegistry",
      "getIdentityRegistry():(address)",
      [],
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }
}

export class ValidationRequestCall extends ethereum.Call {
  get inputs(): ValidationRequestCall__Inputs {
    return new ValidationRequestCall__Inputs(this);
  }

  get outputs(): ValidationRequestCall__Outputs {
    return new ValidationRequestCall__Outputs(this);
  }
}

export class ValidationRequestCall__Inputs {
  _call: ValidationRequestCall;

  constructor(call: ValidationRequestCall) {
    this._call = call;
  }

  get validatorAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get agentId(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get requestUri(): string {
    return this._call.inputValues[2].value.toString();
  }

  get requestHash(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }
}

export class ValidationRequestCall__Outputs {
  _call: ValidationRequestCall;

  constructor(call: ValidationRequestCall) {
    this._call = call;
  }
}

export class ValidationResponseCall extends ethereum.Call {
  get inputs(): ValidationResponseCall__Inputs {
    return new ValidationResponseCall__Inputs(this);
  }

  get outputs(): ValidationResponseCall__Outputs {
    return new ValidationResponseCall__Outputs(this);
  }
}

export class ValidationResponseCall__Inputs {
  _call: ValidationResponseCall;

  constructor(call: ValidationResponseCall) {
    this._call = call;
  }

  get requestHash(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get response(): i32 {
    return this._call.inputValues[1].value.toI32();
  }

  get responseUri(): string {
    return this._call.inputValues[2].value.toString();
  }

  get responseHash(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }

  get tag(): Bytes {
    return this._call.inputValues[4].value.toBytes();
  }
}

export class ValidationResponseCall__Outputs {
  _call: ValidationResponseCall;

  constructor(call: ValidationResponseCall) {
    this._call = call;
  }
}
